server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: cos1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# mustache 를 사용하겠다고 의존성 등록을 하면 아래의 경로가 자동 등록됨
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 724093390547-705u6b8e459j9roatddj02884etvhihl.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          # https://console.cloud.google.com/
          facebook:
            clientId: 564999755323778
            clientSecret: 6fd33b6871800428cbb60dffcfdb3079
            scope:
              - email
              - public_profile
          # https://developers.facebook.com/
          # new app 이 아닌 test app 으로 생성해야 localhost 환경에서 테스트가 가능함
          naver:
            clientId: k5ii5fyTMaA6CIyuAK4h
            clientSecret: yfo7XL0j1_
            scope:
              - name
              - email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/naver
          # https://developers.naver.com/
          kakao:
            clientId: 2cd17b1e33e3d29fefd848ba8bceceb7
            clientSecret: ZwgpqZhCtSZQco5evjKYnKpcVZLlRHfL
            clientAuthenticationMethod: POST
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            # https://developers.kakao.com/

        provider: # naver 는 provider 가 아니기 떄문에 등록을 해주어야함
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response # response 라는 키 값으로 회원 정보가 담긴 json 데이터를 관리해줌
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id